=== dibyendumajumdar/nj/jitbuilder/apigen/schema/api.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id":  "https://raw.githubusercontent.com/eclipse/omr/master/jitbuilder/apigen/schema/api.schema.json",
    "title": "API Description Format",
    "description": "Format for describing framework and library APIs in a way that allows simple generation of language bindings",
    "$comment": "Copyright (c) 2018, 2018 IBM Corp. and others (see LICENSE.md)",
    "$comment": "SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception",
    "type": "object",
    "properties": {
        "project": { "description": "The name of the project or API", "type": "string" },
        "version": {
            "description": "Version of the API",
            "type": "object",
            "properties": {
                "major": { "type": "integer", "minimum": 0 },
                "minor": { "type": "integer", "minimum": 0 },
                "patch": { "type": "integer", "minimum": 0 }
            },
            "required": [ "major", "minor", "patch" ]
        },
        "namespace": { "description": "Namespace containing the API", "type": "array", "items": { "type": "string" } },
        "types": {
            "description": "Definition of datatypes used by the API",
            "type": "array",
            "items": { "$ref": "api-type.schema.json" }
        },
        "fields": {
            "description": "Definition of data fields offered by the API",
            "type": "array",
            "items": { "$ref": "api-field.schema.json" }
        },
        "services": {
            "description": "Definition of services (functions, methods, etc.) offered by the API",
            "type": "array",
            "items": { "$ref": "api-service.schema.json" }
        },
        "classes": {
            "description": "Definition of the classes offered by the API",
            "type": "array",
            "items": { "$ref": "api-class.schema.json" }
        }
    },
    "required": [ "project", "version", "namespace", "types", "fields", "services", "classes" ]
}

=== dibyendumajumdar/nj/jitbuilder/apigen/test/test_sample.json
{
    "project": "Project",
    "version": {
        "major": 0,
        "minor": 0,
        "patch": 0
    },
    "namespace": ["NS1", "NS2"],
    "types": [],
    "fields": [
        {
            "name": "Project_field_1",
            "type": "int32",
            "assign_at_init": true
        },
        {
            "name": "Project_field_2",
            "type": "constString",
            "assign_at_init": false
        }
    ],
    "services": [
        {
            "name": "Project_service_1",
            "overloadsuffix": "overload",
            "flags": [],
            "return": "none",
            "parms": [
                {"name":"Project_service_1_parm_1","type":"int16"},
                {"name":"Project_service_1_parm_2","type":"pointer","attributes":["in_out"]},
                {"name":"Project_service_1_parm_3","type":"double","attributes":["array", "can_be_vararg"],"array-len":"Project_service_1_parm_1"}
            ]
        }
    ],
    "classes": [
        {
            "name": "class_1",
            "short-name": "c1",
            "types": [
                {
                    "name": "class_1_inner_class_1",
                    "short-name": "c1ic1",
                    "types": [],
                    "fields": [],
                    "constructors": [
                        {
                            "name": "",
                            "overloadsuffix": "",
                            "flags": [],
                            "return": "none",
                            "parms": []
                        }
                    ],
                    "services": [],
                    "callbacks": []
                }
            ],
            "fields": [
                {"name":"class_1_field_1","type":"float","assign_at_init":true},
                {"name":"class_1_field_2","type":"double","assign_at_init":true}
            ],
            "constructors": [
                {
                    "name": "",
                    "overloadsuffix": "ctor_overload_1",
                    "flags": [],
                    "return": "none",
                    "parms": []
                }
            ],
            "services": [
                {
                    "name": "class_1_service_1",
                    "overloadsuffix": "",
                    "flags": [ "sets-allocators" ],
                    "return": "constString",
                    "parms": [
                        {"name":"class_1_service_1_parm","type":"constString"}
                    ]
                },
                {
                    "name": "class_1_service_2",
                    "overloadsuffix": "overload",
                    "flags": [ "protected" ],
                    "return": "none",
                    "parms": []
                }
            ],
            "callbacks": [
                {
                    "name": "class_1_callback_1",
                    "overloadsuffix": "",
                    "flags": [],
                    "return": "boolean",
                    "parms": [
                        {"name":"class_1_callback_1_parm","type":"boolean"}
                    ]
                }
            ]
        },
        {
            "name": "class_2",
            "short-name": "c2",
            "extends": "class_1",
            "types": [],
            "fields": [],
            "constructors": [
                {
                    "name": "",
                    "overloadsuffix": "",
                    "flags": [],
                    "return": "none",
                    "parms": []
                }
            ],
            "services": [],
            "callbacks": []
        }
    ]
}
